version: "3.9"

services:
  # APP (PHP + Laravel)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - laravel

  # Banco de Dados
  postgres:
    image: postgres:15
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: projeto_produtos
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

  # Redis (Jobs, Cache)
  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - laravel

  # pgAdmin (gerenciar o banco)
  pgadmin:
    image: dpage/pgadmin4
    container_name: laravel_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - laravel

networks:
  laravel:

volumes:
  postgres_data:
